# Generated by Django 5.2.8 on 2025-11-19 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название скидки/купона"
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Процент скидки/купона",
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID купона для stripe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название налога"),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Налоговая ставка"
                    ),
                ),
                (
                    "stripe_tax_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID налога для stripe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Налог",
                "verbose_name_plural": "Налоги",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("eur", "EUR")], default="usd", max_length=3
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Общая цена элементов",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stripe_app.discount",
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="stripe_app.item", verbose_name="Элементы в заказе"
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stripe_app.tax",
                        verbose_name="Налог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
