# Generated by Django 5.2.8 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0002_discount_tax_item_currency_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("eur", "EUR")],
                default="usd",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание товара"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название товара"),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена товара"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                to="stripe_app.item", verbose_name="Товары в заказе"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая стоимость заказа",
            ),
        ),
    ]
